### ISSUE TITLE
Create a repo (or several) with a lot of sample conflicts to resolve

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#116]
> There could be different methods: via a merge, via a pull, via a rebase, via a "stash pop". In one of my previous lessons, I had a .tar.gz with repo all set up, you just had to git pull to make the conflict. Similar kinds of things could happen.

> All (most?) could be optional or advanced exercises.

This good suggestion moved from #80.

**Comment by bast** [comment]
My thoughts while going through this:
- If we provide a repo with conflicts, we also need to maintain that repo.
- Conflicts created by somebody else first need to be inspected. This has value on its own from history inspection perspective but needs to be explained and takes away time.
- Perhaps there is more learning value if (advanced) participants create conflicts and also explore different ways to resolve them?

**Comment by bast** [comment]
I think that with e32633933d51375ef05a9a73f8f310853678969c we might have enough conflict resolution exercises already.

**Comment by rkdarst** [comment]
I think a ton of conflict resolution practices is useful, but it should be outside the main stream (advanced perhaps) and in a separate repository, maintained separately... with guidance about how inspect the situation to figure out what to do.

What format of them would be good?  My first idea is a repo that has .tar.gz's inside of it, and a script to unpack them all. And a mybinder.org deploy script to unpack them, so that they can be done without local setup.

What do you think?

**Comment by Sabryr** [comment]
What is the way forward in this discussion ?

**Comment by bast** [comment]
We regularly run out of time with this lesson so I am not sure adding more will help. I would rather clarify what we have. If I would add more, it would be #217. We can add an optional conflict resolution exercise but I would not introduce additional repos. In my experience they diverge over time, somebody will forget that the other one exists when updating material.

**Comment by Sabryr** [comment]
I will close this issue as there are ways to create conflicts using current repose.
