### ISSUE TITLE
Misleading illustration of staging & committing

### ISSUE THREAD

**Issue by matuskalas** [coderefinery/git-intro#253]
The illustration/analogy https://github.com/coderefinery/git-intro/blob/gh-pages/img/git_stage_commit.svg is misleading, because the `git add` takes the snapshot, and `git commit` archives it.
 (a bit more complex with `-p`)

"Stages" in the staging area are the snapshots, aren't they?

**Comment by bast** [comment]
Hmm... Yes I can see how it can be misleading. Because we can go back to a staged state but more difficult to go back to a certain focus and indeed commit is more like archiving/saving a state.

**Comment by Sabryr** [comment]
The diagram not meant to be taken literally and as a an one-to-one map how Git works. This is to be used in a early stage where the learner is introduced to Git and informed that we shall do it in two steps. When the lesson goes on, it progresses to a level that commands get natural to the learner. At the end as @matuskalas has demonstrated (from his question it is clearly to me  he has  grasped the concepts correctly) , leaner will be able to raise such questions. Yes, if taken literally it is misleading, i.e. there are many Git facts that will not map to this diagram, another one would be add many files before a final commit. IMO this diagram is OK to have at the entrance.  That is a biased conclusion though.

**Comment by Sabryr** [comment]
Is there anything we should  change in the diagram or my explanation makes scene ? @wikfeldt @bast

**Comment by bast** [comment]
I still find this analogy/illustration useful. But perhaps we can point out its limitations. I see the staging area as "preparation" and this is similar when taking photos. Of course internally, a staged version is already archived.

**Comment by rkdarst** [comment]
I'd like to do some hard thinking and come up with the optimal metaphor.
We have good ones, but there are these little things that make it still
hard to explain...

**Comment by Sabryr** [comment]
Not like words the what it means meant to be be clear, not to confuse (we are not talking about abstract art here).   A common issue with diagrams is that, they has been used as a direct reference to the system not as an concept example. 
Other examples: https://twitter.com/jay_gee/status/703360688618536960 - Create a branch does not make any changes to the Octopus is it ? so if we think along that line we can not use concept reference as one system will newer be identical to another

**Comment by Sabryr** [comment]
I see a good article on pedagogy building up

**Comment by Sabryr** [comment]
I do not like to defend the diagram as I made it. If it helpful we keep it otherwise we remove it. Two things to consider, to narrow the discussion and try to close this issue.
1. Is the diagram helpful in informing the users of the two-step process in a more friendly way ? 
2. Are people taking this literally and distracts them from learning the actual concept ?
3. Is there a better analogy ?

**Comment by bast** [comment]
I don't think we should remove it. But we might replace it but before we replace it, somebody needs to come up with a better suggestion.

What is the benefit of doing this in two steps? I can review the commit "once more" before I "send it off". Do we have some good real-life analogy? Because it's also good to not commit unrelated things (moving boxes, shopping cart) but it's perhaps too early to motivate with avoiding unrelated things, since at this stage we just want to commit changes so we need a good analogy for this stage IMO.

**Comment by Sabryr** [comment]
I am closing this issue and inform to learners to use the diagram as and exact mapping to git but as an example of use of a two-step process. Focus - "collect information" , press take photo - "save it"

**Comment by matuskalas** [comment]
👍🏽 I do like both the previous and the current illustration @sabry-razick! Actually I don't find the first one misleading anymore (sorry for that; they are really about showing a analogous familiar concept of a 2-stage process, and they are both doing that very well🚀

**Comment by Sabryr** [comment]
@matuskalas thank you for your contribution in making this better
