### ISSUE TITLE
Setup 'main' as default branch? 🤶🏽

### ISSUE THREAD

**Issue by matuskalas** [coderefinery/git-intro#352]
Would it be useful (until `main` becomes default in git) to add a requirement for having a "new enough" version of git and setting up `git config --global init.defaultbranch main`?

(mentioned in https://github.com/coderefinery/testing/pull/101)

**Comment by rkdarst** [comment]
for reference: requires version 2.28 (released 2020-07-27).

So as of now, someone using ubuntu LTS must have installed or upgraded in the last six months to have this.  It will take another 1.5 years until the last two Ubuntu versions both have it.  I'm not sure about Mac update cycles.  Clusters and other remote computers are, of course, are much, much slower.

**Comment by frankier** [comment]
This did cause some problems in the workshop, with people ending up with "main" and "master" sometimes.

In the lesson, before the first `git init` is run, could we try asking them to run `git --version`, and

 * If the version is older than a 2.28, explaining to always remember to run `git checkout -b main` as the next step, or `git branch -m master main` if there are already commits. This could be some kind of separate reference section linked out of the main document.
 * If the version is greater than or equal to 2.28, we can just suggest `git config --global init.defaultbranch main`

This information could be added early on, perhaps twice in the git-intro, and also flagged up in the installation instructions.

The current way becomes very confusing, especially when people get to the GitHub lesson. I think switching to main now is worth the disadvantages because it would create greater cohesion between the lessons which is more important.

BTW, I spent some time trying to figure out if there's a way to wrangle defaultbranch behaviour into ancient git. There is an attempt here https://superuser.com/a/1424265 but you would need to reimplement git argument parsing in bash to generalise it to also support the "git init --args DEST" form.
