### ISSUE TITLE
Suggestion for lesson rewrite to start from web and only later move to terminal

### ISSUE THREAD

**Issue by bast** [coderefinery/git-intro#430]
Below I suggest a big rewrite of the Git lesson (days 1 and 2) where we would start from the web and introduce pull requests already on day 1. It would also affect day 3 (https://coderefinery.github.io/git-collaborative/). Of course we can also agree to only implement part of it.

Can you please give **critical feedback and comments** before we do the changes?

## Summary of changes

- Start from web (GitHub)
- Only on day 2 we move to the laptop
- On day 3 we add collaboration
- Introduce good practices from the start with good exercise repositories with
  a good layout and commit messages which we can discuss
- Day 3: add more branch layout to it since we would have more time (freed up
  by introducing pull requests earlier)

## Timeline

- We would try to implement these changes already for the workshop next month

## Motivation for changes

- Learners are more likely to start from an existing repo or to already have some project that is not yet on Git
- Many do not work in the terminal but rather in an IDE or editor
- Making a terminal available on Windows is not always easy
- We try to explain basic concepts in a terminal but they might be easier to explain in a web interface
- It should be possible to participate and learn without a functioning local installation of Git and Bash
- Give everybody the feeling of accomplishment and everybody should be able to
  do the most basic Git/GitHub tasks after the 2-3 half days
- Avoid troubles with main/master naming

## Why we should do it

- We introduce forks and pull requests already on day 1: this can free up time for day 3 to do more interesting things there
- Also the "non-programmers" can benefit from this course
- In future we might not need "Collaborating and sharing using GitHub without command line" as standalone lesson anymore
- Gives more opportunity to "sneak in" some branch design discussions
- Might feel more motivating to see something "real" instead of starting from something empty
- Might make the lesson more interesting and fun for new instructors and helpers to join

## Why we should not do it

- Big rewrite which might exhaust us
- We risk introducing problems which we did not anticipate and observe earlier
- Week 2 lessons might expect that command line Git has been taught
- Maybe too GitHub centric
- If we also try to add GitLab, it might become too much work and too confusing to follow
- Exercise leaders and co-instructors might be surprised by the changes

## Open questions

- Not sure whether we should offer some VS Code track or not
- Will it work and flow if somebody joins only on day 2 or only on day 3?
- Should this rewrite be done in a separate repo?

## Suggested exercises

Day 1 exercises
- 20 min: Fork a repository, browse branches and commits, discuss and answer some questions about the repo
- 20 min: On the web create branches and commits with useful commit messages, optional: release
- 20 min: Merge branches using pull requests, browse and discuss network, optional: resolve conflicts

Day 2 exercises
- 20 min: Configure Git together, clone repo and try some of the commands locally (terminal or editor)
- 30 min: Inspecting history (in web browser or locally)
- 30 min: Saving own work to GitHub/GitLab (web or terminal)

Day 3 exercises
- 30 min: Suggest and review changes within a repository
- 30 min: Suggest and review changes from a fork, update fork

**Comment by rkdarst** [comment]
My thoughts:
* We should do something
* As I think about the above plan, the problem I see is: this doesn't match the way people really work.  Web can show concepts, but it doesn't connect to what people actually need to do quick enough.  How many people would not return after the first day, after being theoretical the first day?

(Aside: I wonder how much of git is hard because we try to be too dogmatic about the right ways to do things?)

Here is my rough proposal:
* Ways to attend
  * As much as possible, support web, VSCode(=codium), and command line.  VSCode will be more work but if it's what people use, we should use it (and they have figured out a practical user interface).   
* Day 1: Your own projects.  Everything you need to know to use git yourself.
  * explore on web to see what a project looks like (recipe book?), clone locally, commit, push.
  * Ex 1: Basic archaeology on the web
  * Ex 2: Config and clone from web, do some commits
  * Ex 3: more commits.  Maybe, make your own repo online, clone, and push. Needs thought.
  * (final wrap up: comments on 'init' yourself
* Day 2: with a small group.  Centralized workflow.  Basically, what a small internal research group could do.
  * Cloning a repo, commit, push.  Simulate a merge conflict, resolve, and push. (this will be hard with a giant course, since we can't simulate small groups where pull-merge-push works, but we can think of something)
  * Ex?: Make own repo, clone, commit, push.  (but this is too similar to yesterday.  Needs thought)
  * Ex?: Merge conflict: Clone our repo, make an edit.  Pull again and see a merge conflict.  Resolve merge, push
  * Ex?: Recovery exercises.  (at least two methods: lose all your work and get to a known state.  Get to known state but save your work as uncommitted changes.)
  * Ex?: More archeology.
* Day 3: Large projects and PRs
  * Clone repo, make branch, PRs.  The usual stuff.
  * Some exercises around pull requests.

This leaves the "right way" to the end but gets to the common way as soon as possible (and that's the point... the right way is dogmatic).  I'm not sure how exactly each of these can be done web/vscode/command line but I bet we can think of most.  And most importantly, I can easily make a recommendation: "Never used git before, watch the 3 hour day 1 CodeRefinery [actually much less, probably closer to 1-1.5 hours] and you learn what you need"

I think all the stuff above needs to be worked out on a board in details (probably somehow combining the plans together), and we need to play with vscode a lot to understand it, but we can do it next week with all the time we have.

**Comment by bast** [comment]
Thank you! Let's work on it on the board next week.
Just wanted to note down some concerns/thoughts that I have:
- many of my "customers"/researchers work in Spyder or R Studio or Notepad++
- some of them do work in the web
- if we leave out pull requests to the end, we have to explain more things and have to deal with failed pushes
- if people start with cloning and pushing on day 1 instead of forking, we have to deal with access and with conflicts and failed pushes
- spending whole day on the web does not have to be theoretical, it would still be exercise-driven and goal-oriented

**Comment by bast** [comment]
Notes from pre-discussion:
- generating form template flattens history
- creating a PR on a fork by default is directed towards central (this might be confusing or hard to explain but also could be satisfying)
- we need good metaphor for forking

**Comment by bast** [comment]
Whiteboard notes from today:
![Uploading git-white-board.jpg…]()

**Comment by bast** [comment]
![git-white-board](https://github.com/coderefinery/git-intro/assets/5120679/0cc4a337-2260-4eee-88f5-844d3d262de5)

Notes from today.

**Comment by Sabryr** [comment]
Should we have look what others are doing ?, e.g. youtube search

**Comment by bast** [comment]
![screenshot](https://github.com/coderefinery/git-intro/assets/5120679/23dfecbd-bbb9-4c88-966a-d9ff8f7fefaf)

**Comment by bast** [comment]
(copied notes from another document)

# (day 1)
## Motivation
(mostly same as before, but move to google docs example)
## Your first project
* Our recipe book
  - README.md
  - LICENSE
  - recipes/
    - few existing recipees
  - gitignore?
    - GH lets me upload files anyway without warning 
  - (private and public copy)
  - added day 3: action to verify
    - check markdown
    - or check for certain ingredient 
  - added day 3: pages deploy
* Make a copy to work on (fork repository)
* Exercise 1a: Fork (20 min)
  * Do the fork
  * This i
## Archaeology part 1
* Exercise 1b: Archeology
  * Explore a few things (copy from "inspecting history")
    * "grep" (which foods include a certain ingredient)
    * annotate (who has contributed to this recipe)
      * at which commit did an ingredient get introduced or modified? 
    * Contributors page (Who all has contributed?)
    * How old is each recipe, and how many changes? (look at history)
    * When was each recipe last modified? (file browser)
    * Can you use these recipes yourself? (license)
    * Browse issues and pull requests, any idea what that might be good for?
    * Browse commit history: are commit messages understandable?
  * Preparation:
    * RB creates starting repo
    * we need a group of staff preparing this
    * each adds one and maybe changes one recipe 
    * we need two versions: repo and repo-recorded

## Modify your copy (commit)
* 
* Exercise: commit
  * create a branch and commit to it
  * maybe also commit to main
  * browse network
  * compare branches
  * compare commits



## Merge branches and contribute to the project
* Exercise: Merge branches with PR
  * select from which to which
  * be careful about whether this is towards main on your copy or the repo where we forked from
  * browse network
  * optional: try also to send a PR towards the central repo (we merge few of those)
  
* Demo:
  * conflict
  * delete branches
  * create release (or optional exercise step)
* Discussion: Doing this locally.  We will start here tomorrow.
* Quiz:
  * how to find out which branches are safe to delete? 


# (day 2)

* What is Git, and what is a Git repository? (from git-intro)
* Configuring Git command line (from git-intro)
* Exercise: config/clone/commit/branch


## Archaeology part 2
(copy from archeology)
* Exercise: Arch part 2
* Exercise: push to clone / remote add push to default, OR init add commit remote add push

**Comment by bast** [comment]
Now working on the `lesson-redesign` branch: https://coderefinery.github.io/git-intro/branch/lesson-redesign/

**Comment by bast** [comment]
We have basically now done this. What remains are filling in some blanks.
